### PR TITLE
Internal: find an available port to connect the python rpc server

### LINKED ISSUE #676: Find an open port for the python server to connect to
Currently the port is hard coded which might conflict with other apps and/or if the rpc server wasn't killed correctly because of a crash

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #676

### CODE REVIEW

File: src/client/client-constants.ts [hunk 1]
```diff
@@ -26,10 +44,17 @@ const urls = {
 
 const isAsar = process.mainModule.filename.indexOf("app.asar") !== -1;
 
+const pythonServerPort = {
+    // dev: Promise.resolve(8765),
```
Comment (timotheeguerin) [inline src/client/client-constants.ts]: change
