### PR TITLE
Fix bug with query cache loading items too litle at the time

### LINKED ISSUE #297: QueryCache saving next link make it ignore the new params
Repro step:
Set pool picker maxResults to `2`
Go to pool list it will now only load pools 2 by 2.

### PR DESCRIPTION
**Pull request by timotheeguerin**
This is done by changing the way the query cache works. It will now just be used to show the initial items but items will still be loaded in the background(This should also make sure the data is not out of date)
fix #297

### CODE REVIEW

File: app/components/job/details/job-progress-status/job-progress-status.component.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export class JobProgressStatusComponent implements OnChanges, OnDestroy {
     constructor(private poolService: PoolService, private nodeService: NodeService) {
         this.poolData = poolService.get(null);
         this.data = nodeService.list(null, {
-            maxResults: 1000,
+            pageSize: 1000,
```
Comment (paselem) [inline app/components/job/details/job-progress-status/job-progress-status.component.ts]: I don't think you need to set this since the default is 1000.

Comment (timotheeguerin) [inline app/components/job/details/job-progress-status/job-progress-status.component.ts]: we actually override the default to be 50 for all call, so I need to force it back
